# Generated by Django 5.0.2 on 2024-02-29 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_boss_name_alter_element_name_alter_region_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='code',
        ),
    ]
