# Generated by Django 5.0.2 on 2024-02-29 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_element_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localspecialty',
            name='code',
        ),
    ]
