# Generated by Django 5.0.2 on 2024-02-29 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_localspecialty_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enemy',
            old_name='elite',
            new_name='common',
        ),
        migrations.AddField(
            model_name='trophy',
            name='insert_code',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resource',
            name='n1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='n2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='n3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='n4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
