# Generated by Django 5.0.2 on 2024-02-29 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_elite_enemy_common_trophy_insert_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enemy',
            old_name='common',
            new_name='is_common',
        ),
        migrations.AddField(
            model_name='character',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app.book'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='boss',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app.boss'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='common',
            field=models.ForeignKey(default=1, limit_choices_to={'is_common': True}, on_delete=django.db.models.deletion.PROTECT, to='app.enemy'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='element',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app.element'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='local_specialty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app.localspecialty'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='name',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='rarity',
            field=models.PositiveSmallIntegerField(choices=[(4, 4), (5, 5)], default=4),
        ),
        migrations.AddField(
            model_name='character',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app.region'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='stat_atk',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='stat_def',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='stat_hp',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='stat_value',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='weapon_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app.weapontype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='weekly_boss',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app.weeklyboss'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='weekly_drop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app.weeklydrop'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enemy',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
