# Generated by Django 5.0.2 on 2024-02-29 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_common_enemy_is_common_character_book_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='weekly_drop',
            field=models.ForeignKey(limit_choices_to={'weekly_boss': models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.weeklyboss')}, on_delete=django.db.models.deletion.PROTECT, to='app.weeklydrop'),
        ),
    ]
