# Generated by Django 5.0.2 on 2024-02-29 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_character_weekly_drop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='weekly_boss',
        ),
        migrations.AddField(
            model_name='character',
            name='model',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Tall Male'), (1, 'Tall Female'), (2, 'Medium Male'), (3, 'Medium Female'), (4, 'Short Female')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='stat',
            field=models.PositiveSmallIntegerField(choices=[(0, 'ATK%'), (1, 'DEF%'), (2, 'HP%'), (3, 'CRIT Rate'), (4, 'CRIT DMG'), (5, 'Elemental Mastery'), (6, 'Energy Recharge'), (7, 'Healing Bonus'), (8, 'Physical DMG Bonus'), (9, 'Pyro DMG Bonus'), (10, 'Hydro DMG Bonus'), (11, 'Dendro DMG Bonus'), (12, 'Electro DMG Bonus'), (13, 'Anemo DMG Bonus'), (14, 'Cryo DMG Bonus'), (15, 'Geo DMG Bonus')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='character',
            name='weekly_drop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.weeklydrop'),
        ),
    ]
