# Generated by Django 5.0.2 on 2024-02-29 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_character_weekly_boss_character_model_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='character',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.model'),
        ),
        migrations.AlterField(
            model_name='character',
            name='stat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.stat'),
        ),
    ]
