# Generated by Django 5.0.2 on 2024-02-29 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_model_stat_alter_character_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='version',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='character',
            name='stat_value',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
