# Generated by Django 5.0.2 on 2024-02-29 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_character_version_alter_character_stat_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enemy',
            name='is_common',
        ),
        migrations.AddField(
            model_name='enemy',
            name='is_elite',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='stat',
            name='is_weapon_stat',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weapon',
            name='common',
            field=models.ForeignKey(default=1, limit_choices_to={'is_elite': False}, on_delete=django.db.models.deletion.PROTECT, related_name='common', to='app.enemy'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weapon',
            name='elite',
            field=models.ForeignKey(default=1, limit_choices_to={'is_elite': True}, on_delete=django.db.models.deletion.PROTECT, related_name='elite', to='app.enemy'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weapon',
            name='is_wish_only',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='weapon',
            name='max',
            field=models.PositiveSmallIntegerField(choices=[(0, ''), (1, 1)], default=0),
        ),
        migrations.AddField(
            model_name='weapon',
            name='name',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weapon',
            name='rarity',
            field=models.PositiveSmallIntegerField(choices=[(4, 4), (5, 5)], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weapon',
            name='stat',
            field=models.ForeignKey(default=1, limit_choices_to={'is_weapon_stat': True}, on_delete=django.db.models.deletion.PROTECT, to='app.stat'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weapon',
            name='stat_atk',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weapon',
            name='stat_value',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weapon',
            name='trophy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app.trophy'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weapon',
            name='version',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weapon',
            name='weapon_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app.weapontype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='character',
            name='common',
            field=models.ForeignKey(limit_choices_to={'is_elite': False}, on_delete=django.db.models.deletion.PROTECT, to='app.enemy'),
        ),
        migrations.AlterField(
            model_name='character',
            name='rarity',
            field=models.PositiveSmallIntegerField(choices=[(4, 4), (5, 5)]),
        ),
    ]
