# Generated by Django 5.0.2 on 2024-03-01 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_enemy_is_common_enemy_is_elite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='inv_order',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
