# Generated by Django 5.0.2 on 2024-03-01 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_element_inv_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.book'),
        ),
        migrations.AlterField(
            model_name='character',
            name='boss',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.boss'),
        ),
        migrations.AlterField(
            model_name='character',
            name='weekly_drop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.weeklydrop'),
        ),
    ]
