# Generated by Django 5.0.2 on 2024-03-05 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_character_book_alter_character_boss_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boss',
            options={'verbose_name_plural': 'bosses'},
        ),
        migrations.AlterModelOptions(
            name='enemy',
            options={'verbose_name_plural': 'enemies'},
        ),
        migrations.AlterModelOptions(
            name='localspecialty',
            options={'verbose_name_plural': 'local specialties'},
        ),
        migrations.AlterModelOptions(
            name='trophy',
            options={'verbose_name_plural': 'trophies'},
        ),
        migrations.AlterModelOptions(
            name='weeklyboss',
            options={'verbose_name_plural': 'weekly bosses'},
        ),
    ]
