# Generated by Django 5.0.2 on 2024-03-06 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_image_static'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Static',
            new_name='Constant',
        ),
    ]
