# Generated by Django 5.0.2 on 2024-03-06 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_rename_static_constant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='format',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.URLField(),
        ),
    ]
