# Generated by Django 5.0.2 on 2024-03-06 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_image_format_alter_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='format',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
