# Generated by Django 5.0.2 on 2024-02-20 00:42

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='inventory',
            field=models.JSONField(default=users.models.inventory_default),
        ),
    ]
