# Generated by Django 5.0.2 on 2024-02-21 02:43

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_inventory_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='inventory',
        ),
        migrations.AddField(
            model_name='data',
            name='data',
            field=models.JSONField(default=users.models.data_default),
        ),
        migrations.AddField(
            model_name='data',
            name='traveler',
            field=models.CharField(choices=[('M', 'Aether'), ('F', 'Lumine')], default='M', max_length=1),
        ),
    ]
