# Generated by Django 4.2.11 on 2025-07-26 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Boss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'bosses',
            },
        ),
        migrations.CreateModel(
            name='Constant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculation_data', models.JSONField(blank=True, null=True)),
                ('drop_rates', models.JSONField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('gem', models.CharField(max_length=50)),
                ('inv_order', models.PositiveSmallIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Enemy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('low', models.CharField(max_length=50)),
                ('mid', models.CharField(max_length=50)),
                ('high', models.CharField(max_length=50)),
                ('is_elite', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'enemies',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('url', models.CharField(max_length=100)),
                ('format', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('n1', models.CharField(blank=True, max_length=50, null=True)),
                ('n2', models.CharField(blank=True, max_length=50, null=True)),
                ('n3', models.CharField(blank=True, max_length=50, null=True)),
                ('n4', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('is_weapon_stat', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Trophy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=50)),
                ('n2', models.CharField(max_length=50)),
                ('n3', models.CharField(max_length=50)),
                ('n4', models.CharField(max_length=50)),
                ('n5', models.CharField(max_length=50)),
                ('insert_code', models.BooleanField()),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.region')),
            ],
            options={
                'verbose_name_plural': 'trophies',
            },
        ),
        migrations.CreateModel(
            name='WeaponType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WeeklyBoss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'weekly bosses',
            },
        ),
        migrations.CreateModel(
            name='WeeklyDrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=50)),
                ('weekly_boss', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.weeklyboss')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('version', models.DecimalField(decimal_places=1, max_digits=3)),
                ('is_wish_only', models.BooleanField(default=True)),
                ('rarity', models.PositiveSmallIntegerField(choices=[(4, 4), (5, 5)])),
                ('max', models.PositiveSmallIntegerField(choices=[(0, ''), (1, 1)], default=0)),
                ('stat_atk', models.PositiveSmallIntegerField()),
                ('stat_value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('common', models.ForeignKey(limit_choices_to={'is_elite': False}, on_delete=django.db.models.deletion.PROTECT, related_name='common', to='api.enemy')),
                ('elite', models.ForeignKey(limit_choices_to={'is_elite': True}, on_delete=django.db.models.deletion.PROTECT, related_name='elite', to='api.enemy')),
                ('stat', models.ForeignKey(limit_choices_to={'is_weapon_stat': True}, on_delete=django.db.models.deletion.PROTECT, to='api.stat')),
                ('trophy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.trophy')),
                ('weapon_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.weapontype')),
            ],
        ),
        migrations.CreateModel(
            name='LocalSpecialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('inv_order', models.PositiveSmallIntegerField(default=0)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.region')),
            ],
            options={
                'verbose_name_plural': 'local specialties',
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('version', models.DecimalField(decimal_places=1, max_digits=3)),
                ('rarity', models.PositiveSmallIntegerField(choices=[(4, 4), (5, 5)])),
                ('stat_hp', models.PositiveSmallIntegerField()),
                ('stat_atk', models.PositiveSmallIntegerField()),
                ('stat_def', models.PositiveSmallIntegerField()),
                ('stat_value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.book')),
                ('boss', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.boss')),
                ('common', models.ForeignKey(limit_choices_to={'is_elite': False}, on_delete=django.db.models.deletion.PROTECT, to='api.enemy')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.element')),
                ('local_specialty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.localspecialty')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.model')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.region')),
                ('stat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.stat')),
                ('weapon_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.weapontype')),
                ('weekly_drop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.weeklydrop')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.region'),
        ),
    ]
